name: Build test iso 
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: run make iso script
        run: |
          sudo apt-get update
          sudo apt-get install mtools
          sudo apt-get install mkisofs
          sudo apt-get install xorriso
          git clone https://github.com/Mr0btain/x13s_iso_make.git
          cd x13s_iso_make
          chmod +x ./make_iso.sh
          bash ./make_iso.sh
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          path: ubuntu-kinetic-arm64-custom.iso
          
